name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TIME: 2021-05-04T21:00:00

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Get current date and time
        id: datetime
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: "NUXT_ENV_BUILD_TIME=${{ steps.datetime.outputs.date }} yarn run generate"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
